"""esquema inicial: 15 tablas

Revision ID: 6a5cf736fa47
Revises: 
Create Date: 2026-06-08 19:38:08.870494

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a5cf736fa47'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('WORLD_CUP', 'CONTINENTAL', 'QUALIFIER', 'NATIONS_LEAGUE', 'FRIENDLY', name='competition_kind'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=120), nullable=False),
    sa.Column('source', sa.Enum('MARTJ42', 'ELORATINGS', 'API_FOOTBALL', 'STATSBOMB', 'ODDS_API', name='data_source'), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'source', name='uq_sync_resource_source')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fifa_code', sa.String(length=3), nullable=True),
    sa.Column('confederation', sa.Enum('UEFA', 'CONMEBOL', 'CONCACAF', 'CAF', 'AFC', 'OFC', name='confederation'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fifa_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('elo_rating',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'rating_date', name='uq_elo_team_date')
    )
    op.create_index(op.f('ix_elo_rating_rating_date'), 'elo_rating', ['rating_date'], unique=False)
    op.create_index(op.f('ix_elo_rating_team_id'), 'elo_rating', ['team_id'], unique=False)
    op.create_table('team_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MARTJ42', 'ELORATINGS', 'API_FOOTBALL', 'STATSBOMB', 'ODDS_API', name='data_source'), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_team_alias_source_external')
    )
    op.create_table('tournament_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'season_year', 'name', name='uq_group_comp_season_name')
    )
    op.create_table('group_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tournament_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'team_id', name='uq_group_team')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('neutral_site', sa.Boolean(), nullable=False),
    sa.Column('stage', sa.Enum('GROUP', 'ROUND_OF_32', 'ROUND_OF_16', 'QUARTER_FINAL', 'SEMI_FINAL', 'THIRD_PLACE', 'FINAL', 'QUALIFIER', 'FRIENDLY', name='match_stage'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINISHED', name='match_status'), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('went_to_extra_time', sa.Boolean(), nullable=False),
    sa.Column('went_to_penalties', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['tournament_group.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_match_date'), 'match', ['match_date'], unique=False)
    op.create_table('goal_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('scorer_name', sa.String(length=120), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('own_goal', sa.Boolean(), nullable=False),
    sa.Column('penalty', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_team_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_stats_match_team')
    )
    op.create_table('odds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('market_type', sa.Enum('MATCH_1X2', 'OVER_UNDER', 'OUTRIGHT_WINNER', 'GROUP_ADVANCE', name='market_type'), nullable=False),
    sa.Column('outcome_code', sa.String(length=20), nullable=True),
    sa.Column('outcome_team_id', sa.Integer(), nullable=True),
    sa.Column('line', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bookmaker', sa.String(length=60), nullable=False),
    sa.Column('decimal_odds', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_captured_at'), 'odds', ['captured_at'], unique=False)
    op.create_index(op.f('ix_odds_match_id'), 'odds', ['match_id'], unique=False)
    op.create_table('prediction',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.Enum('MATCH_1X2', 'OVER_UNDER', 'OUTRIGHT_WINNER', 'GROUP_ADVANCE', name='market_type'), nullable=False),
    sa.Column('outcome_code', sa.String(length=20), nullable=True),
    sa.Column('probability', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_match_id'), 'prediction', ['match_id'], unique=False)
    op.create_table('shootout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('value_signal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('odds_id', sa.BigInteger(), nullable=False),
    sa.Column('edge', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('ev', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('kelly_fraction', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('recommended_stake', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['odds_id'], ['odds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('value_signal_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.Enum('PAPER', 'REAL', name='bet_mode'), nullable=False),
    sa.Column('stake', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('odds_taken', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'VOID', name='bet_status'), nullable=False),
    sa.Column('settled_result', sa.String(length=20), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['value_signal_id'], ['value_signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet_log')
    op.drop_table('value_signal')
    op.drop_table('shootout')
    op.drop_index(op.f('ix_prediction_match_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_odds_match_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_captured_at'), table_name='odds')
    op.drop_table('odds')
    op.drop_table('match_team_stats')
    op.drop_table('goal_event')
    op.drop_index(op.f('ix_match_match_date'), table_name='match')
    op.drop_table('match')
    op.drop_table('group_team')
    op.drop_table('tournament_group')
    op.drop_table('team_alias')
    op.drop_index(op.f('ix_elo_rating_team_id'), table_name='elo_rating')
    op.drop_index(op.f('ix_elo_rating_rating_date'), table_name='elo_rating')
    op.drop_table('elo_rating')
    op.drop_table('team')
    op.drop_table('sync_log')
    op.drop_table('model_version')
    op.drop_table('competition')
    # ### end Alembic commands ###
