"""M2: new columns source_event_id, commence_time, kickoff_at, prediction.line

Revision ID: ce5f5f676dea
Revises: 04aaa08229f6
Create Date: 2026-06-09 23:17:56.686273

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ce5f5f676dea"
down_revision: str | None = "04aaa08229f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("kickoff_at", sa.DateTime(), nullable=True))
    op.add_column("odds", sa.Column("source_event_id", sa.String(length=80), nullable=True))
    op.add_column("odds", sa.Column("commence_time", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_odds_source_event_id"), "odds", ["source_event_id"], unique=False)
    op.add_column("prediction", sa.Column("line", sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prediction", "line")
    op.drop_index(op.f("ix_odds_source_event_id"), table_name="odds")
    op.drop_column("odds", "commence_time")
    op.drop_column("odds", "source_event_id")
    op.drop_column("match", "kickoff_at")
    # ### end Alembic commands ###
